### ISSUE TITLE
Expose QCoreApplication properties for Dialogs

### ISSUE THREAD

**Issue by Korvox** [woboq/qmetaobject-rs#113]
The Dialogs QML module uses QSettings on some platforms for things like window dimensions and remembering previous locations but doesn't work without set values on the qApp for 'organizationName', 'organizationDomain', and 'applicationName'.

> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
> 19:35:49 [WARN] file:///usr/lib/qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")

Having methods to set these, maybe even inferring applicationName from the `CARGO_PKG_NAME` would make these modules work.

This would also let the qt.labs.settings module to work as well.

**Comment by ratijas** [comment]
+1
Had to work around by writing wrappers for C++ classes on my own just to set application's name etc. But then I quickly realized I could just load QML Settings module into engine first, and then proceed to the main QML file.

See: https://github.com/InnopolisUniversity/innometrics-agent-os-linux/blob/af156740f9a6af2b6385482a386af81b720055da/innometrics-app/qml/settings/AppQtSettings.qml and https://github.com/InnopolisUniversity/innometrics-agent-os-linux/blob/af156740f9a6af2b6385482a386af81b720055da/innometrics-app/src/main.rs#L35
