### ISSUE TITLE
Request for two new labels

### ISSUE THREAD

**Issue by asdf8dfafjk** [woboq/qmetaobject-rs#131]
Hello,

I recently used this and was pleasantly surprised that it works so well.  Do you have any "pure rust" and "good-first-issue" issues  that I can tackle? (I should note that I am a good CPP programmer too but the `Q` style of CPP programming is not something I have a lot of experience with)

**Comment by ratijas** [comment]
Hi @asdf8dfafjk,

You could start by reading our design consideration outlined in issues #81, #83 and #91.
Meanwhile, do explore source code and look for any improvement opportunities.

For example, #93 and #96 seem like an easy routines.

**Comment by asdf8dfafjk** [comment]
Thank you. I intend to spend time on this

**Comment by ratijas** [comment]
Done via discussion #161.
