### ISSUE TITLE
Allow linking against QtQuickControls2 (and more?)

### ISSUE THREAD

**Issue by tnibler** [woboq/qmetaobject-rs#140]
It would be very nice and convenient to enable linking against more qt libraries through feature flags in the qttypes crate. Personally, I only have a need for QtQuickControls2 ([change here](https://github.com/woboq/qmetaobject-rs/commit/308836a20f3149e3e0032762b7a759cb39712b81)), but maybe it would be good to add more libraries as well?

**Comment by ogoffart** [comment]
Yes, that makes total sense!

**Comment by tnibler** [comment]
From https://doc.qt.io/qt-5/qtmodules.html, the libraries we could link against are:

 - `QtQuickControls2`
 - `QtWidgets`
 - `QtMultimedia` and `QtMultimediaWidgets`
 - `QtSql`
 - `QtTest`

Should I just open a PR with all of them?

**Comment by ratijas** [comment]
What would programmers do with them without at least some basic wrappers and support beyond linking?

**Comment by tnibler** [comment]
I guess most of them would only be useful if you want to reuse existing Qt code with some `cpp!` macro glue.
