### ISSUE TITLE
failed to run custom build command for `qttypes v0.2.0`

### ISSUE THREAD

**Issue by FuSoftware** [woboq/qmetaobject-rs#141]
Hello, 

I'm trying to use the qmetaobject crate on Windows, but so far I've been unable to compile it due to a compilation error in `qttypes`. I have tested it with MSVC 2015, 2017 and 2019 with the same error. 

I have Qt6.1.0 MSVC 2019 installed on my machine and the binaries in the PATH. Is this a known issue ? I couldn't find anything related so far.

Is Windows supported for this Rust lib ?

Compilation logs: 
```
Caused by:
  process didn't exit successfully: `J:\Prog\Rust\qml-test\target\release\build\qttypes-4a84ce9c1f8d7a72\build-script-build` (exit code: 1)
  --- stderr


  error occurred: ToolExecError: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "D:\\Prog\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\qttypes-0.2.0" "-I" "F:/Qt/Qt5.9.0/6.1.0/msvc2019_64/include" "-W4" "-FoJ:\\Prog\\Rust\\qml-test\\target\\release\\build\\qttypes-a2fc4f6bd491854e\\out\\rust_cpp\\cpp_closures.o" "-c" "J:\\Prog\\Rust\\qml-test\\target\\release\\build\\qttypes-a2fc4f6bd491854e\\out\\rust_cpp\\cpp_closures.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

**Comment by ogoffart** [comment]
Hi,

The log you pasted does not contains the actual compilation error.
But i'm pretty sure the problem is that Qt 6 is not yet supported.

**Comment by FuSoftware** [comment]
Hello,

I also tried with Qt 5.12.2 with the same error

**Comment by FuSoftware** [comment]
nvm, I re-installed the 5.12.2 Qt binaries and it works now, I guess I had messed something in my Qt install. Good to know Qt 6.1.0 isn't supported yet
