### ISSUE TITLE
Disable WebEngine example on Windows + MinGW

### ISSUE THREAD

**Issue by ratijas** [woboq/qmetaobject-rs#167]
## Summary

Qt does not ship pre-built WebEngine component for Windows MinGW target, so we should find a way to exclude it from the list of default targets on that platform's target triple.

## Description

Running simple `cargo build` in qmetaobject-rs repository on Windows with MinGW environment results in build failure:

```
   Compiling qmetaobject v0.2.2 (C:\Users\ratijas\projects\qmetaobject-rs\qmetaobject)
   Compiling graph v0.1.0 (C:\Users\ratijas\projects\qmetaobject-rs\examples\graph)
The following warnings were emitted during compilation:

warning: src\webengine.rs:4:10: fatal error: QtWebEngine/QtWebEngine: No such file or directory
warning:  #include <QtWebEngine/QtWebEngine>
warning:           ^~~~~~~~~~~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `qmetaobject v0.2.2 (C:\Users\ratijas\projects\qmetaobject-rs\qmetaobject)`

Caused by:
  process didn't exit successfully: `C:\Users\ratijas\projects\qmetaobject-rs\target\debug\build\qmetaobject-4c86368b25d7a0a5\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("i686-pc-windows-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-gnu")
[...]
  running: "g++.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-I" "C:\\Users\\ratijas\\projects\\qmetaobject-rs\\qmetaobject" "-I" "C:/Qt/5.15.2/mingw81_32/include" "-Wall" "-Wextra" "-std=c++11" "-o" "C:\\Users\\ratijas\\projects\\qmetaobject-rs\\target\\i686-pc-windows-gnu\\debug\\build\\qmetaobject-54d9dbd8cb0dbb47\\out\\rust_cpp\\cpp_closures.o" "-c" "C:\\Users\\ratijas\\projects\\qmetaobject-rs\\target\\i686-pc-windows-gnu\\debug\\build\\qmetaobject-54d9dbd8cb0dbb47\\out\\rust_cpp\\cpp_closures.cpp"
  cargo:warning=src\webengine.rs:4:10: fatal error: QtWebEngine/QtWebEngine: No such file or directory
  cargo:warning= #include <QtWebEngine/QtWebEngine>
  cargo:warning=          ^~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit code: 1
```

## Workaround

Manually specify packages to exclude from workspace builds:

```powershell
cargo build --workspace --exclude webengine
```

## Solution

I don't think politely asking Qt to ship pre-built WebEngine for MinGW is a viable solution, so let's try to mitigate the issue with Rust tools.

Cargo supports workspace-level package selection via [`default-members`](https://doc.rust-lang.org/cargo/reference/workspaces.html#package-selection) key. Cons:
- Disables package for all platforms and targets;
- Requires typing in every package twice, except excluded ones. You might think that there's an `exclude` key for this task, but turns out it's for something else — preventing directories entirely from even being scanned by cargo.

Anyway, I tried with _Cargo.toml_ and _.cargo/config.toml_, and none of that works with triple-specific sections.

**Comment by jwintz** [comment]
If I may, the same fix would be awesome for Qt >= 6.0.0, and that holds so far with 6.2.0 alpha ;-)
