### ISSUE TITLE
qttypes build failure on Fedora

### ISSUE THREAD

**Issue by Be-ing** [woboq/qmetaobject-rs#197]
Fedora ships the qmake executable as /usr/bin/qmake-qt5. qttypes only searches for an executable named `qmake`.

```
error: failed to run custom build command for `qttypes v0.2.3`

Caused by:
  process didn't exit successfully: `/home/be/sw/whisperfish/target/debug/build/qttypes-fb973ac7213bde24/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=QT_INCLUDE_PATH
  cargo:rerun-if-env-changed=QT_LIBRARY_PATH

  --- stderr
  thread 'main' panicked at 'Error: Failed to execute qmake. Make sure 'qmake' is in your path!
  Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/be/.cargo/registry/src/github.com-1ecc6299db9ec823/qttypes-0.2.3/build.rs:113:21
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

This is easy to work around by creating a symlink called `qmake` somewhere in PATH pointing to /usr/bin/qmake-qt5.

How should this be handled by qttypes? A hack could be added to look for qmake-qt5 just for Fedora. But looking at qttype's build.rs, it doesn't actually build anything with qmake; it only uses qmake to locate Qt. So maybe it would be better to use another method to locate Qt. `find_package(Qt5)` with CMake works fine to locate Qt5 on Fedora, however that would bring in a dependency on CMake which is not necessarily present on every OS where Qt is installed.

**Comment by ratijas** [comment]
Hi, @Be-ing!  Nice avatar, btw ;-)

While I am not familiar with Fedora's packaging system, I see many Qt5 tools these days are shipping with an optional "-qt5" suffix — on Arch Linux too.

You don't have to create system-wide symlinks or modify your installation in any way. If you take a look at the [docs on qttypes](https://docs.rs/qttypes/0.2.3/qttypes/index.html#finding-qt) or read its buils.rs code, you'll see that

> you can specify a `QMAKE` environment variable with the absolute path of the `qmake` executable which will be used to query these paths

Of course, we also could add one extra name to check for automatically.

**Comment by ratijas** [comment]
Prioritized as Low, because the workaround is available and quite trivial.

**Comment by Be-ing** [comment]
If it is not only Fedora doing this then I think it would be reasonable to check for `qmake-qt5` if `qmake` is not found..

**Comment by ogoffart** [comment]
I guess checking for qmake-qt5 if qmake is not found makes sense.

**Comment by ogoffart** [comment]
maybe the error message could also tell to use the QMAKE env variable,  or perhaps even link to the documentation of qttypes on how Qt is found.
