### ISSUE TITLE
failed to run custom build command for `qttypes v0.2.6`

### ISSUE THREAD

**Issue by hu76589** [woboq/qmetaobject-rs#215]
when compile the example Greeter ,it shows error:
error: failed to run custom build command for `qttypes v0.2.6`

Caused by:
  process didn't exit successfully: `D:\rust\qtdemo\target\debug\build\qttypes-008567fa4a6d71b7\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=QT_INCLUDE_PATH
  cargo:rerun-if-env-changed=QT_LIBRARY_PATH
  cargo:rerun-if-env-changed=QMAKE

  --- stderr
  thread 'main' panicked at 'Error: Failed to execute qmake. Make sure 'qmake' is in your path!
  系统找不到指定的文件。 (os error 2)', D:\app\rust\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\qttypes-0.2.6\build.rs:29:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

Why? and what should i do ?

**Comment by ogoffart** [comment]
> Error: Failed to execute qmake. Make sure 'qmake' is in your path!

Looks like Qt is not installed, or that the PATH env variable is not set to include qmake

**Comment by ogoffart** [comment]
Closing this issue.
The error message should be explicit enough.
