### ISSUE TITLE
Undefined Behaviour with QByteArray

### ISSUE THREAD

**Issue by Ayush1325** [woboq/qmetaobject-rs#216]
I am encountering some weird issues with a function that returns QByteArray. I am trying to write a wrapper for `applicationDomain()` function of [klocalizedstring](https://api.kde.org/frameworks/ki18n/html/classKLocalizedString.html) in [KI18n KDE Framework](https://api.kde.org/frameworks/ki18n/html/index.html).
Here is a test I have written:
```rust
#[test]
fn application_domain() {
    const APPLICATION_DOMAIN: &str = "KI18n";
    KLocalizedString::set_application_domain(APPLICATION_DOMAIN);
    let domain = KLocalizedString::application_domain();

    assert_eq!(domain.to_str().unwrap(), "KI18n");
}
```
Now this fails which is not much of a problem. The error I get is this:
```
---- application_domain stdout ----
thread 'application_domain' panicked at 'assertion failed: `(left == right)`
  left: `"KI18ntests/klocalizedstring_tests.rsapplication_domain"`,
 right: `"KI18n"`', tests/klocalizedstring_tests.rs:10:5
```
However, when I try to print the `domain` QByteArray, I actually get the correct output but the error changes:
```
---- application_domain stdout ----
KI18n
tests/klocalizedstring_tests.rsapplication_domain
thread 'application_domain' panicked at 'assertion failed: `(left == right)`
  left: `"KI18n\ntests/klocalizedstring_tests.rsapplication_domain"`,
 right: `"KI18n"`', tests/klocalizedstring_tests.rs:11:5
```
If I print `domain` using the debug trait, the error again changes:
```
---- application_domain stdout ----
KI18n

thread 'application_domain' panicked at 'assertion failed: `(left == right)`
  left: `"KI18n\n"`,
 right: `"KI18n"`', tests/klocalizedstring_tests.rs:11:5
```
So I'm not exactly sure what is going on here. In all the cases, printing does seem to produce the correct output with `println!` but the assert somehow seems to compare some completely different values.

**Comment by ogoffart** [comment]
What's the code of `KLocalizedString::set_application_domain`?
It looks like the size of the string is not passed properly.

**Comment by Ayush1325** [comment]
@ogoffart Thanks, I think the problem was occurring since I was trying to convert `&str` to `char*`. I found one solution using `std::ffi::CString` instead of `&str` and that seems to resolve the problem.
