### ISSUE TITLE
Why do enums use repr(u32) instead of repr(c)?

### ISSUE THREAD

**Issue by Ayush1325** [woboq/qmetaobject-rs#228]
So recently I was trying to use some Qt enums and flags in rust. After looking through the code in qttypes, it seems the enums are using `repr(u32)` instead of `repr(c)` which I would have expected with FFI. So I was wondering about the reason for doing so. Is it a C++/Rust FFI thing or a QT thing? 
[Here](https://doc.rust-lang.org/reference/type-layout.html#reprc-field-less-enums) is the Rust doc for C-style enums.

**Comment by ogoffart** [comment]
I don't remember why I did it like that.
I gues `#[repr(C)]` should also be Ok.

**Comment by Ayush1325** [comment]
Ok. I also think we should change `repr(u32)` to `repr(C)` too.
