### ISSUE TITLE
qttypes/build.rs rebuilds every time, even if no changes

### ISSUE THREAD

**Issue by AdrianEddy** [woboq/qmetaobject-rs#252]
`qttypes/build.rs` contains this code at the bottom:
```rust
println!("cargo:rerun-if-changed=src/lib.rs");
println!("cargo:rerun-if-changed=src/core/primitives.rs");
println!("cargo:rerun-if-changed=src/core/qbytearray.rs");
println!("cargo:rerun-if-changed=src/core/qstring.rs");
println!("cargo:rerun-if-changed=src/core/qurl.rs");
println!("cargo:rerun-if-changed=src/gui/qcolor.rs");
```
The `core` directory was renamed to `qtcore` and the file structure also changed, so this should be updated accordingly

**Comment by ogoffart** [comment]
Ah yes, i notice it now.

(Ideally i should change the cpp-build crate so it does that automatically)

**Comment by ogoffart** [comment]
Released a new version of qttypes with the fix
