### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Supreeeme** [woboq/qmetaobject-rs#289]
[This commit](https://github.com/woboq/qmetaobject-rs/commit/4457e59be1b0185ea85b4802e65e08558644f927) (and the commit before) fix compilation issues with Qt 6.5. That seems like it'd be worthy of a new release, or at least a new minor version. Would it be possible to get one?

**Comment by ogoffart** [comment]
yes, this was long overdue.  Thanks for the reminder
0.2.9 was released
