### ISSUE TITLE
When using cargo workspaces, QML files need to be in multiple locations for qrc! macro

### ISSUE THREAD

**Issue by Ace4896** [woboq/qmetaobject-rs#30]
Hi, I have been trying out this crate recently for some side projects of mine. Everything was OK until I tried using this in a project that used cargo workspaces, where I had trouble compiling since the QML files could not be found. I had to put the QML files in both the root project directory and the workspace directory to workaround the problem. Is this something that could be fixed?

I made a quick project using the Greeter example (where the QML code is in its own file) demonstrating the issue: [qml_rust_workspaces.zip](https://github.com/woboq/qmetaobject-rs/files/2994185/qml_rust_workspaces.zip)

`qml` folder only in the `my_app` workspace (upon checking the error with a local copy of the crate, it was unable to find the file):

```
error: proc macro panicked
  --> my_app/src/main.rs:16:1
   |
16 | / qrc!(
17 | |     my_resources,
18 | |     "main" {
19 | |         "qml/Test.qml"
20 | |     },
21 | | );
   | |__^
   |
   = help: message: Canot open file qml/Test.qml
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `my_app`.

To learn more, run the command again with --verbose.
jon@jon-Aspire-A715-71G:~/Documents/Programming/QML/qml_rust_workspaces$ tree
.
├── Cargo.lock
├── Cargo.toml
└── my_app
    ├── Cargo.toml
    ├── qml
    │   └── Test.qml
    └── src
        └── main.rs
```

`qml` folder only in the root directory:

```
error: couldn't read my_app/src/../qml/Test.qml: No such file or directory (os error 2)
  --> my_app/src/main.rs:16:1
   |
16 | / qrc!(
17 | |     my_resources,
18 | |     "main" {
19 | |         "qml/Test.qml"
20 | |     },
21 | | );
   | |__^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `my_app`.

To learn more, run the command again with --verbose.
jon@jon-Aspire-A715-71G:~/Documents/Programming/QML/qml_rust_workspaces$ tree
.
├── Cargo.lock
├── Cargo.toml
├── my_app
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── qml
    └── Test.qml
```

**Comment by ogoffart** [comment]
I guess i need to find a better way to look for file, and do it relative to some specific directory. (File directory? crate base directory?)
I'm open to suggestion on how to do that. Is there an environment variable set perhaps? or a way to get the actual file name?
(in 
https://github.com/woboq/qmetaobject-rs/blob/master/qmetaobject_impl/src/qrc_impl.rs#L232 )

**Comment by Ace4896** [comment]
Hmm, I looked around for some environment variables that could help; there isn't a specific one for workspaces, but there is the [`CARGO_MANIFEST_DIR`](https://doc.rust-lang.org/cargo/reference/environment-variables.html) variable that gets the directory which the current workspace's `Cargo.toml` is in. Maybe the files could be searched for relative to this directory?

This would let each workspace have their own resource files, which would cleanup the crate base directory.
