### ISSUE TITLE
Embedded vulkan to the  bindings

### ISSUE THREAD

**Issue by happydpc** [woboq/qmetaobject-rs#34]
I want to use qt/qml ecosystem in rust and also with vulkan graphic api like Gfx-rs. Is there any way I can make this?

**Comment by ogoffart** [comment]
I'm not an expert in this matter, but I believe Qt/Qml can work with a vulkan backend.
Perhaps there is some api that need to be exposed such as https://doc-snapshots.qt.io/qt5-dev/qvulkaninstance.html , but wrapping the nevessary part of this API should not be too difficult.  PR welcome.

**Comment by happydpc** [comment]
Ok, thank you. I will have a try.

**Comment by ratijas** [comment]
Link above is dead, and a lot of things have changed including new shiny Qt6 with QRhi, the Qt Rendering Hardware Interface. I believe, if anyone would be really interested in such wrappers, they'll have to open a new more specific issue, or just send a pull-request.

https://www.qt.io/blog/graphics-in-qt-6.0-qrhi-qt-quick-qt-quick-3d
