### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by Ace4896** [woboq/qmetaobject-rs#36]
Should an error occur in a function of a Rust QML object, how would I pass the error information back to the QML side?

**Comment by ogoffart** [comment]
Good question.
I suppose that in most case, we would return a null value (eg. 0 or empty string or something like that).  And perhaps set an error property or emit an error signal.

**Comment by Ace4896** [comment]
Ah, that's a good suggestion; I'll give that a go later. I guess I was over-complicating things by trying to see what would happen if I used things like `panic!` and `expect` with QML's try/catch.

**Comment by Ace4896** [comment]
Sorry for leaving this open, finally got the chance to try out your suggestion and it's worked out quite nicely.
