### ISSUE TITLE
Add support for QAbstractItemModel base classes

### ISSUE THREAD

**Issue by tones111** [woboq/qmetaobject-rs#4]
In order to use a tree view the underlying model must inherit from QAbstractItemModel which is currently not supported.

I have started a naive attempt to add support, but am struggling getting the generated code to compile.  One challenge is that the index and parent methods return a QModelIndex which I believe is causing the build to fail with

cargo:warning=.../target/debug/build/qmetaobject-90f6bc2d732d83be/out/rust_cpp/cpp_closures.cpp: In instantiation of ‘union rustcpp::return_helper<QModelIndex>::container::<unnamed>’:
cargo:warning=.../target/debug/build/qmetaobject-90f6bc2d732d83be/out/rust_cpp/cpp_closures.cpp:20:9:   required from ‘struct rustcpp::return_helper<QModelIndex>::container’
cargo:warning=.../target/debug/build/qmetaobject-90f6bc2d732d83be/out/rust_cpp/cpp_closures.cpp:27:45:   required from here
.../target/debug/build/qmetaobject-90f6bc2d732d83be/out/rust_cpp/cpp_closures.cpp:20:19: error: ‘rustcpp::return_helper<T>::container::<unnamed union>::memory’ has incomplete type
cargo:warning=         union { T memory; };
cargo:warning=                   ^~~~~~

I'm not sure what/where support for returning that type needs to go.  Any suggestions?

Thanks

**Comment by ogoffart** [comment]
Difficult to say without seeing the code.
Maybe some includes are missing? 
Surely the documentation can be improved.

**Comment by ogoffart** [comment]
Was fixed with #5
