### ISSUE TITLE
Building through QTCreator?

### ISSUE THREAD

**Issue by Sandvich** [woboq/qmetaobject-rs#40]
Is this possible at the moment?
I want to write applications for SailfishOS using this, which uses a customised version of QTCreator to build and deploy the code. I could probably work out how to do it manually, but I'd prefer to keep the current pipeline if possible.

**Comment by bundyo** [comment]
Currently Sailfish is still at Qt 5.6, so QMetaObject probably wouldn't work. I'm also waiting for Sailfish's transition to Qt 5.9, but it is yet to happen.

**Comment by Sandvich** [comment]
It's a minor version bump, so I would _hope_ that it's still compatible... But the question that I'm asking is more that, if we assume for a moment that QMetaObject works perfectly with this crate/Sailfish itself, is it possible to integrate the build system with the Sailfish SDK?

**Comment by bundyo** [comment]
Probably.

I wouldn't consider Qt 5.x releases as minor. There's probably a reason for the `Requires Qt >= 5.8` on the front page of this project. :wink:

**Comment by bundyo** [comment]
Here is a list of new and obsolete classes in just 5.8:

https://doc.qt.io/qt-5/newclasses58.html
https://doc.qt.io/qt-5/obsoleteclasses.html

**Comment by ogoffart** [comment]
There are some function that are used from Qt 5.8, so it would need some porting, and dsabling some feature, to support older Qt version.

As for Qt Creator, the goal is to do the development in rust, so it is meant to be build with cargo. (using cargo build)
I guess you could manage to get a qmake script to run cargo build from qmake.  And somehow tell QtCreator what are the binary that need to be deployed.  But that is out of the scope of this project.

**Comment by Sandvich** [comment]
Oof, I didn't realise that. I was assuming it used the same major.minor.patch syntax as most.
Thanks for the info, both of you. I'll have to investigate the build system further.
