### ISSUE TITLE
Support for QQmlComponent

### ISSUE THREAD

**Issue by agentsim** [woboq/qmetaobject-rs#55]
I'd like to be able use `QQmlComponent` from within Rust, mainly so I can dynamically load some Qml and then do stuff with the `QObject` I get back from the `create` method.

I've tried a couple of ideas, but run into problems. For example, `QQmlComponent` is `Q_DISABLE_COPY` which seems to make it difficult to access in Rust code without having to put it on the heap.

I'm happy to do the work for this feature, but I would appreciate some guidance in terms of how best to implement it.

**Comment by ogoffart** [comment]
Hi,

> For example, QQmlComponent is Q_DISABLE_COPY which seems to make it difficult to access in Rust code without having to put it on the heap.

That's right, you need to put it on the heap. I do not think this is an issue because QQmlComponent makes lots of heap allocation as well, so one more or less does not make a big difference.

So the rust equivalent of `QQmlComponent` should hold a raw pointer, and the Drop should delete it.

You can do something like  `cpp_class!(unsafe struct QQmlComponentInternal as "std::unique_ptr<QQmlComponent>"); ` and `pub struct QQmlComponent(QQmlComponentInternal)`  so that Drop is automatically managed.

**Comment by agentsim** [comment]
Thanks for the pointers. I've got the basics in place, but I've run into a snag supporting signals. Here's snippet of my code:

```
    pub fn status_changed_signal() -> CppSignal<fn(status: ComponentStatus)> {
        unsafe { CppSignal::new(cpp!([] -> SignalCppRepresentation as "SignalCppRepresentation"  {
            return &QQmlComponent::statusChanged;
        }))}
    }
```

From what I can tell the problem is ```SignalCppRepresentation``` cannot be constructed unless the signal is a member of ```QObject``` directly, i.e. not of a derived class as in this case. The error is below

> 
> cargo:warning=/Users/tmurison/src/qmetaobject-rs/qmetaobject/qmetaobject_rust.hpp:33:5: note: candidate template ignored: could not match 'QObject' against 'QQmlComponent'
> cargo:warning=    SignalCppRepresentation(R (QObject::*cpp_signal)(Args...))
> cargo:warning=    ^

**Comment by ogoffart** [comment]
Ah, that's right.

Maybe the constructor of SignalCppRepresentation should be changed to something like this:

```cpp
template<typename R, typename Object, typename ...Args>
    SignalCppRepresentation(R (Object::*cpp_signal)(Args...))
        : cpp_signal(*reinterpret_cast<void (QObject::**)()>(&cpp_signal)) { }
```
