### ISSUE TITLE
Crates.io

### ISSUE THREAD

**Issue by keeslinp** [woboq/qmetaobject-rs#6]
Are there any plans to release this to crates.io? I did a quick search and was unable to find anything so far. If I'm mistaken could you point me in the right direction?

Cool idea though, can't wait to play around with it.

**Comment by ogoffart** [comment]
This is still an early pre-alpha.
The raison it is not yet on crates.io is that it depends on a fork of the cpp crate and would need https://github.com/mystor/rust-cpp/pull/31 to be merged.
Also there is a Qt dependency, i'm not quite sure how to specify that in the Cargo.toml file.

**Comment by nbigaouette** [comment]
PR was merged a couple hours ago.

As for the dependency on Qt, you can take a look at what qmlrs is doing through a build script: https://github.com/cyndis/qmlrs/blob/master/build.rs
Nothing in Cargo.toml needs to be changed...

**Comment by florianjacob** [comment]
If there are any questions regarding the `build.rs` Qt dependency integration, please ask, I'm lurking here. :wink:

This looks way better than what I hoped to achieve with my qmlrs rewrite based on [libqmlbind](https://github.com/seanchas116/libqmlbind), so I'll probably abandon that and will try to help out here.

**Comment by ogoffart** [comment]
Right, now everything needed is merged in rust-cpp. I guess there is the need of a version increase and publish it on crates.io

**Comment by ogoffart** [comment]
Now that cpp 0.4 was released, I uploaded the crate to crates.io:  https://crates.io/crates/qmetaobject
