### ISSUE TITLE
qt_property NOTIFY signal with parameter

### ISSUE THREAD

**Issue by Thra11** [woboq/qmetaobject-rs#72]
Using Qt's `Q_PROPERTY` macro in C++, it allows the `NOTIFY` signal to have either zero or one parameters. qmetaobject-rs allows you to declare a signal with a parameter:
```
qt_signal!(value: String)
```
but `qt_property!` doesn't seem to accept it as a `NOTIFY` signal:
```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
  --> src/foo.rs:11:52
   |
3  | #[derive(Default, QObject)]
   |                   ------- defined here
...
11 |     value: qt_property!(u32; READ get_value NOTIFY value_changed),
   |                                                    ^^^^^^^^^^^^^ expected 1 parameter
```
None of the examples use a signal with a parameter in a property. It is not clear from the documentation whether it is intentionally unsupported or just doesn't currently work.

**Comment by ogoffart** [comment]
Thanks for your bug report. 
This was just not implemented. 
Done in commit cd26083
