### ISSUE TITLE
todo example is broken

### ISSUE THREAD

**Issue by vandenoever** [woboq/qmetaobject-rs#9]
Running `cargo run` in `examples/todos` prints
```
rust(17717)/default unknown: qrc:/todos/qml/main.qml:49: Error: Unknown method return type: (  )
```

**Comment by ogoffart** [comment]
Strange, it works for me.
Are you using master? What's your version of rust?

**Comment by ogoffart** [comment]
in qmetaobject_impl/src/qobject_impl.rs, line 47  there is

```
"()" | "( )" => 43,
```

Can you try to replace it with

```
"()" | "( )" | "(  )" => 43,
```

i.e: add a variant with two spaces.
   
Not sure why you would have an extra space there.  Maybe nightly have different formatting.
But that shows that one probably use another way to parse known types than just string matching

**Comment by vandenoever** [comment]
The variant with two spaces fixes the problem.

**Comment by vandenoever** [comment]
The version of rust: rustc 1.30.0-nightly (2224a42c3 2018-09-17)

**Comment by vandenoever** [comment]
Where do you run travis?

**Comment by ogoffart** [comment]
Travis-ci.org
